# Generated by Django 5.1.15 on 2026-07-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Homepage banner. Landscape ~1920×1080. Leave blank to use a destination photo.', null=True, upload_to='brand/'),
        ),
    ]
