# Generated by Django 5.2.16 on 2026-07-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='charity_body',
            field=models.TextField(blank=True, default='Travel should leave a place better than it found it. A part of every journey with us goes back into the communities we love — building classrooms, training young people with real skills, and supporting vulnerable children and the environment across Tanzania.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='charity_enabled',
            field=models.BooleanField(default=True, help_text="Show the 'Giving back' section on the homepage."),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='charity_image',
            field=models.ImageField(blank=True, help_text='Photo for the giving-back section. Landscape ~1200×800.', null=True, upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='charity_stat1',
            field=models.CharField(blank=True, default='3 classrooms built', max_length=60),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='charity_stat2',
            field=models.CharField(blank=True, default='120+ children supported', max_length=60),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='charity_stat3',
            field=models.CharField(blank=True, default='Youth skills training', max_length=60),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='charity_title',
            field=models.CharField(blank=True, default='Giving back to our community', max_length=120),
        ),
    ]
